In [167]:
import sklearn.datasets
import sklearn.linear_model as lm
import sklearn.model_selection as ms
(X,y)=sklearn.datasets.load_diabetes(return_X_y=True, as_frame=True)
X, y = sklearn.datasets.load_breast_cancer(return_X_y=True,as_frame=True)


In [168]:
X_train, X_test, y_train, y_test=ms.train_test_split(X, y, test_size=.20,random_state=123)

In [175]:
def evaluate_classification_model(y_train, y_pred_train, y_test, y_pred_test):
    performance_df = pd.DataFrame({'Error_metric': ['Accuracy','Precision','Recall'],
                               'Train': [accuracy_score(y_train, y_pred_train),
                                         precision_score(y_train, y_pred_train),
                                         recall_score(y_train, y_pred_train)],
                               'Test': [accuracy_score(y_test, y_pred_test),
                                        precision_score(y_test, y_pred_test),
                                        recall_score(y_test, y_pred_test)]})
    
    pd.options.display.float_format = '{:.2f}'.format

    df_train = pd.DataFrame({'Real': y_train, 'Predicted': y_pred_train})
    df_test  = pd.DataFrame({'Real': y_test,  'Predicted': y_pred_test})

    return performance_df, df_train, df_test

In [182]:
from sklearn import tree
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
from sklearn.metrics import plot_confusion_matrix

model=tree.DecisionTreeClassifier(criterion='gini', max_depth=None, 
                            min_samples_split=2, min_samples_leaf=1, 
                            max_features=None, random_state=None)
model.fit(X_train, y_train)
y_pred=model.predict(X_test)
y_pred_train=model.predict(X_train)
##calling the function
error_metrics_df,y_train_vs_predicted, \
    y_test_vs_predicted=evaluate_classification_model(y_train, y_pred_train,
                                                    y_test, y_pred)
error_metrics_df

Error_metric  Train  Test
0     Accuracy   1.00  0.96
1    Precision   1.00  0.97
2       Recall   1.00  0.97

In [163]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=2)
model.fit(X_train, y_train)
y_pred=model.predict(X_test)
y_pred_train=model.predict(X_train)

In [164]:
y_pred

array([171. , 126.5, 252.5, 173.5, 115.5, 183. , 197. , 140.5, 100. ,
        64.5, 154. , 139.5, 207.5, 241.5, 275.5, 136. ,  86.5, 170.5,
       111.5, 262. , 178.5, 303.5, 143. , 111.5,  63.5, 185. ,  88.5,
       123. , 151. , 214. ,  77. , 143.5,  75.5, 253.5, 184. ,  81.5,
        81.5,  93. , 257. ,  76.5, 189.5, 135.5, 121. , 130. , 150.5,
       253. , 142.5,  99.5,  72.5, 209. , 124.5,  94.5, 117.5, 262. ,
        80.5, 258.5, 274.5, 198.5, 110. ,  70. ,  86.5, 122. , 197. ,
       269. , 172. ,  90. ,  49.5, 143.5, 135. , 127. ,  58. ,  72. ,
       132.5, 278. ,  55.5, 153.5,  76. , 129.5, 152. , 138.5, 111.5,
       159. , 144. , 280.5, 286.5, 201. , 173.5,  69. , 148. ])

In [124]:
model= lm.LinearRegression()
model.fit(X_train, y_train)
y_pred=model.predict(X_test)
y_pred_train=model.predict(X_train)

In [125]:
pd.Series([model.intercept_]+ list(model.coef_),index=["Intercept"]+list(X_train.columns))

Intercept    152.05
age           -6.19
sex         -225.24
bmi          505.20
bp           295.62
s1          -826.05
s2           466.91
s3           130.74
s4           252.95
s5           691.08
s6           111.20
dtype: float64

In [126]:
model.predict(X_test)

array([162.26359467, 155.48747839, 227.01019671, 164.63583097,
       158.78861876, 135.27411288, 253.95946355, 106.30662813,
       103.03631134, 114.33330776, 123.87775522, 183.76354732,
       163.00541455, 203.26084844, 214.91810729, 174.49695156,
       108.43475278, 145.38313077, 175.78816988, 191.42525183,
       164.57232464, 233.24090956, 140.03825949,  73.79751056,
       129.98678458, 189.7593074 ,  99.60413529,  99.22486195,
       158.34182642, 184.63831369,  81.93551519, 238.22291295,
       208.12075731, 210.13292762, 199.08373866,  94.83582711,
        93.49289059,  99.17948241, 228.27847992, 101.50596652,
       192.67553228,  81.54468369, 103.23825593, 147.13568637,
       111.39328423, 215.7577106 ,  80.45897342,  75.04534093,
       100.72245569, 217.41160041,  69.28173936, 115.45236404,
       175.51938644, 195.88993672, 139.8423833 , 197.26642367,
       220.21419051, 170.768533  , 194.81047154, 190.59958364,
       138.06597191, 121.09270082, 234.55652657, 203.16

In [132]:
import numpy as np
import sklearn.metrics as metrics
def evaluate_regression_model(y_train, y_pred_train, y_test, y_pred_test):

    ME_train = np.mean(y_train - y_pred_train)
    ME_test  = np.mean(y_test - y_pred_test)

    MAE_train = metrics.mean_absolute_error(y_train,y_pred_train)
    MAE_test  = metrics.mean_absolute_error(y_test,y_pred_test)

    MSE_train = metrics.mean_squared_error(y_train,y_pred_train)
    MSE_test  = metrics.mean_squared_error(y_test,y_pred_test)

    RMSE_train = np.sqrt(MSE_train)
    RMSE_test  = np.sqrt(MSE_test)

    MAPE_train = np.mean((np.abs(y_train- y_pred_train) / y_train)* 100.)
    MAPE_test  = np.mean((np.abs(y_test-y_pred_test) / np.exp(y_test))* 100.)

    R2_train = metrics.r2_score(y_train,y_pred_train)
    R2_test  = metrics.r2_score(y_test,y_pred_test)

    adjusted_R2_train = 1 - (1-R2_train)*(len(y_train)-1)/(len(y_train)-X_train.shape[1]-1)
    adjusted_R2_test = 1 - (1-R2_test)*(len(y_test)-1)/(len(y_test)-X_test.shape[1]-1)
    
    metrics_df = pd.DataFrame({'Error_metric': ['Mean error','Mean absolute error','Mean squared error',
                                             'Root mean squared error','Mean absolute percentual error',
                                             'R2','adjusted_R2'],
                            'Train': [ME_train, MAE_train, MSE_train, RMSE_train, MAPE_train, R2_train,adjusted_R2_train],
                            'Test' : [ME_test, MAE_test , MSE_test, RMSE_test, MAPE_test, R2_test,adjusted_R2_test]})

    pd.options.display.float_format = '{:.2f}'.format

    y_train_vs_predicted = pd.DataFrame({'Real': y_train, 'Predicted': y_pred_train})
    y_test_vs_predicted  = pd.DataFrame({'Real': y_test,  'Predicted': y_pred_test})

    return metrics_df, y_train_vs_predicted, y_test_vs_predicted

In [133]:
perforamnce,y_train_vs_predicted, y_test_vs_predicted=evaluate_regression_model(y_train, model.predict(X_train),y_test,y_pred)
perforamnce


Error_metric   Train    Test
0                      Mean error   -0.00    0.42
1             Mean absolute error   43.60   42.88
2              Mean squared error 2908.99 2724.24
3         Root mean squared error   53.94   52.19
4  Mean absolute percentual error   39.38    0.00
5                              R2    0.50    0.57
6                     adjusted_R2    0.49    0.51

In [155]:
import sklearn.linear_model as lm

def evaluate_multiple_regression_models(X_train,y_train,X_test,y_test):
    models={"LinearRegression":lm.LinearRegression(),"Lasso":lm.Lasso(),"Ridge":lm.Ridge(),"ElasticNet":lm.ElasticNet()}
    performances=[]

    for key in models.keys():
        models[key].fit(X_train, y_train)
        y_pred=models[key].predict(X_test)
        y_pred_train=models[key].predict(X_train)

        perforamnce,y_train_vs_predicted, y_test_vs_predicted=evaluate_regression_model(y_train, y_pred_train,y_test,y_pred)
        perforamnce.columns=["Error_metric",key+"_Train", key+"_Test"]
        performances.append(perforamnce)

    reg_models_err_metrics_df=pd.concat(performances,axis=1)
    del performances; 
    reg_models_err_metrics_df = reg_models_err_metrics_df.loc[:,~reg_models_err_metrics_df.columns.duplicated()]
    return reg_models_err_metrics_df

evaluate_multiple_regression_models(X_train,y_train,X_test,y_test)

Error_metric  LinearRegression_Train  \
0                      Mean error                   -0.00   
1             Mean absolute error                   43.60   
2              Mean squared error                 2908.99   
3         Root mean squared error                   53.94   
4  Mean absolute percentual error                   39.38   
5                              R2                    0.50   
6                     adjusted_R2                    0.49   

   LinearRegression_Test  Lasso_Train  Lasso_Test  Ridge_Train  Ridge_Test  \
0                   0.42         0.00       -1.68         0.00       -0.13   
1                  42.88        53.19       53.92        48.39       50.81   
2                2724.24      3882.87     3981.37      3357.30     3553.20   
3                  52.19        62.31       63.10        57.94       59.61   
4                   0.00        49.14        0.00        44.38        0.00   
5                   0.57         0.33        0.37         0.42        0.44   
6                   0.51         0.32        0.29         0.41        0.36   

   ElasticNet_Train  ElasticNet_Test  
0              0.00            -1.44  
1             64.80            68.41  
2           5784.21          6249.92  
3             76.05            79.06  
4             60.42             0.00  
5              0.01             0.01  
6             -0.02            -0.12

In [74]:
y_pred

array([162.26359467, 155.48747839, 227.01019671, 164.63583097,
       158.78861876, 135.27411288, 253.95946355, 106.30662813,
       103.03631134, 114.33330776, 123.87775522, 183.76354732,
       163.00541455, 203.26084844, 214.91810729, 174.49695156,
       108.43475278, 145.38313077, 175.78816988, 191.42525183,
       164.57232464, 233.24090956, 140.03825949,  73.79751056,
       129.98678458, 189.7593074 ,  99.60413529,  99.22486195,
       158.34182642, 184.63831369,  81.93551519, 238.22291295,
       208.12075731, 210.13292762, 199.08373866,  94.83582711,
        93.49289059,  99.17948241, 228.27847992, 101.50596652,
       192.67553228,  81.54468369, 103.23825593, 147.13568637,
       111.39328423, 215.7577106 ,  80.45897342,  75.04534093,
       100.72245569, 217.41160041,  69.28173936, 115.45236404,
       175.51938644, 195.88993672, 139.8423833 , 197.26642367,
       220.21419051, 170.768533  , 194.81047154, 190.59958364,
       138.06597191, 121.09270082, 234.55652657, 203.16